spring:
  profiles:
    active: dev
  application:
    name: administrative-system-backend
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false