spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
  security:
    user:
      name: root
      password: root
  cors:
    origins:
      - "http://127.0.0.1:5500"
    methods:
      - "POST"
      - "GET"
      - "OPTIONS"
      - "PUT"
    headers:
      - "*"
server:
  port: 8080