package com.gg.administrative_system_backend.order.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CfdiUsage {
    G01("G01", "ADQUISICIÓN DE MERCANCÍAS"),
    G02("G02", "DEVOLUCIONES, DESCUENTOS O BONIFICACIONES"),
    G03("G03", "GASTOS EN GENERAL"),
    I01("I01", "CONSTRUCCIONES"),
    I02("I02", "MOBILIARIO Y EQUIPO DE OFICINA POR INVERSIONES"),
    I03("I03", "EQUIPO DE TRANSPORTE"),
    I04("I04", "EQUIPO DE CÓMPUTO Y ACCESORIOS"),
    I05("I05", "DADOS, TROQUELES, MOLDES, MATRICES Y HERRAMENTAL"),
    I06("I06", "COMUNICACIONES TELEFÓNICAS"),
    I07("I07", "COMUNICACIONES SATELITALES"),
    D01("D01", "HONORARIOS MÉDICOS, DENTALES Y GASTOS HOSPITALARIOS"),
    D02("D02", "GASTOS MÉDICOS POR INCAPACIDAD O DISCAPACIDAD"),
    D03("D03", "GASTOS FUNERALES"),
    D04("D04", "DONATIVOS"),
    D05("D05", "INTERESES REALES EFECTIVAMENTE PAGADOS"),
    D06("D06", "APORTACIONES VOLUNTARIAS AL SAR"),
    D07("D07", "PRIMAS POR SEGUROS DE GASTOS MÉDICOS"),
    D08("D08", "GASTOS DE TRANSPORTACIÓN ESCOLAR OBLIGATORIA"),
    D09("D09", "DEPÓSITOS EN CUENTAS PARA EL AHORRO, PRIMAS QUE TENGAN COMO BASE PLANES DE PENSIONES"),
    D10("D10", "PAGOS POR SERVICIOS EDUCATIVOS (COLEGIATURAS)"),
    S01("S01", "SIN EFECTOS FISCALES");
    private final String code;
    private final String description;
}
